/*
Authress

Testing ResourcePermissionsApi

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package test

import (
	"context"
	"net/url"
	"testing"

	authress "github.com/authress/authress-sdk.go"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_authress_ResourcePermissionsApi(t *testing.T) {

	url, _ := url.Parse("https://auth.yourdomain.com")
	authressClient := authress.NewAuthressClient(authress.AuthressSettings{
		AuthressApiUrl: url, 
	})

	t.Run("Test ResourcePermissionsApi GetPermissionedResource", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var resourceUri string

		resp, httpRes, err := authressClient.ResourcePermissions.GetPermissionedResource(context.Background(), resourceUri).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ResourcePermissionsApi GetPermissionedResources", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := authressClient.ResourcePermissions.GetPermissionedResources(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ResourcePermissionsApi GetResourceUsers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var resourceUri string

		resp, httpRes, err := authressClient.ResourcePermissions.GetResourceUsers(context.Background(), resourceUri).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ResourcePermissionsApi UpdatePermissionedResource", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var resourceUri string

		httpRes, err := authressClient.ResourcePermissions.UpdatePermissionedResource(context.Background(), resourceUri).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
