/*
Authress

Testing ResourcePermissionsApi

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package authress

import (
	"context"
	"testing"

	authress "github.com/authress/authress-sdk.go"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_authress_ResourcePermissionsApi(t *testing.T) {

	authressClient := authress.AuthressClient.New(AuthressSettings{})

	t.Run("Test ResourcePermissionsApi GetPermissionedResource", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var resourceUri string

		resp, httpRes, err := apiClient.ResourcePermissions.GetPermissionedResource(context.Background(), resourceUri).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ResourcePermissionsApi GetPermissionedResources", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ResourcePermissions.GetPermissionedResources(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ResourcePermissionsApi GetResourceUsers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var resourceUri string

		resp, httpRes, err := apiClient.ResourcePermissions.GetResourceUsers(context.Background(), resourceUri).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ResourcePermissionsApi UpdatePermissionedResource", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var resourceUri string

		httpRes, err := apiClient.ResourcePermissions.UpdatePermissionedResource(context.Background(), resourceUri).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
