/*
Authress

Testing InvitesApi

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package authress

import (
	openapiclient "//"
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_authress_InvitesApi(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InvitesApi CreateInvite", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Invites.CreateInvite(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvitesApi DeleteInvite", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var inviteId string

		httpRes, err := apiClient.Invites.DeleteInvite(context.Background(), inviteId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvitesApi GetInvite", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var inviteId string

		resp, httpRes, err := apiClient.Invites.GetInvite(context.Background(), inviteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvitesApi RespondToInvite", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var inviteId string

		resp, httpRes, err := apiClient.Invites.RespondToInvite(context.Background(), inviteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
