/*
Authress

Testing InvitesApi

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package test

import (
	"context"
	"net/url"
	"testing"

	authress "github.com/authress/authress-sdk.go"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_authress_InvitesApi(t *testing.T) {

	url, _ := url.Parse("https://auth.yourdomain.com")
	authressClient := authress.NewAuthressClient(authress.AuthressSettings{
		AuthressApiUrl: url, 
	})

	t.Run("Test InvitesApi CreateInvite", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := authressClient.Invites.CreateInvite(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvitesApi DeleteInvite", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var inviteId string

		httpRes, err := authressClient.Invites.DeleteInvite(context.Background(), inviteId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvitesApi GetInvite", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var inviteId string

		resp, httpRes, err := authressClient.Invites.GetInvite(context.Background(), inviteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvitesApi RespondToInvite", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var inviteId string

		httpRes, err := authressClient.Invites.RespondToInvite(context.Background(), inviteId).Execute()

		require.Nil(t, err)
		// require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
