/*
Authress

Testing InvitesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package authress

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "//"
)

func Test_authress_InvitesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InvitesAPIService CreateInvite", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InvitesAPI.CreateInvite(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvitesAPIService DeleteInvite", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inviteId string

		httpRes, err := apiClient.InvitesAPI.DeleteInvite(context.Background(), inviteId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvitesAPIService GetInvite", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inviteId string

		resp, httpRes, err := apiClient.InvitesAPI.GetInvite(context.Background(), inviteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvitesAPIService RespondToInvite", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inviteId string

		resp, httpRes, err := apiClient.InvitesAPI.RespondToInvite(context.Background(), inviteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
