/*
Authress

Testing TenantsApi

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package authress

import (
	"context"
	"testing"

	authress "github.com/authress/authress-sdk.go"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_authress_TenantsApi(t *testing.T) {

	authressClient := authress.AuthressClient.New(AuthressSettings{})

	t.Run("Test TenantsApi CreateTenant", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Tenants.CreateTenant(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TenantsApi DeleteTenant", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var tenantId TenantId

		httpRes, err := apiClient.Tenants.DeleteTenant(context.Background(), tenantId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TenantsApi GetTenant", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var tenantId TenantId

		resp, httpRes, err := apiClient.Tenants.GetTenant(context.Background(), tenantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TenantsApi GetTenants", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.Tenants.GetTenants(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TenantsApi UpdateTenant", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var tenantId TenantId

		resp, httpRes, err := apiClient.Tenants.UpdateTenant(context.Background(), tenantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
