/*
Authress

Testing ResourcePermissionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package authress

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "//"
)

func Test_authress_ResourcePermissionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ResourcePermissionsAPIService GetPermissionedResource", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceUri string

		resp, httpRes, err := apiClient.ResourcePermissionsAPI.GetPermissionedResource(context.Background(), resourceUri).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ResourcePermissionsAPIService GetPermissionedResources", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ResourcePermissionsAPI.GetPermissionedResources(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ResourcePermissionsAPIService GetResourceUsers", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceUri string

		resp, httpRes, err := apiClient.ResourcePermissionsAPI.GetResourceUsers(context.Background(), resourceUri).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ResourcePermissionsAPIService UpdatePermissionedResource", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceUri string

		httpRes, err := apiClient.ResourcePermissionsAPI.UpdatePermissionedResource(context.Background(), resourceUri).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
